### ISSUE TITLE
About the order for "sum" and "abs" in End.py

### ISSUE THREAD

**Issue by bregmangh** [EIDOSlab/entangling-disentangling-bias#2]
Nice work! But I'm a little confused. According to equation (7) in the paper, in End.py:
orthogonal_loss += torch.abs(torch.sum(gram * bias_mask)) 
should be:
orthogonal_loss += torch.sum(torch.abs(gram * bias_mask)) 
??

**Comment by carloalbertobarbano** [comment]
Hi, sorry for the delay in the response! I was on vacation. 

You are correct, this comes from an older version of our codebase. However, when using ReLU activations the two forms are equivalent.
